-- MySQL Script generated by MySQL Workbench
-- Sun Mar  6 17:49:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portal_cidadao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portal_cidadao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portal_cidadao` DEFAULT CHARACTER SET utf8 ;
USE `portal_cidadao` ;

-- -----------------------------------------------------
-- Table `portal_cidadao`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_cidadao`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `nome_completo` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_cidadao`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_cidadao`.`empresas` (
  `id_empresas` INT NOT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_empresas`),
  UNIQUE INDEX `login_empresa_UNIQUE` (`login` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_cidadao`.`reclamacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_cidadao`.`reclamacoes` (
  `id_reclamacoes` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `data_reclamacao` DATETIME NOT NULL,
  `fk_usuarios` INT NOT NULL,
  `fk_empresas` INT NOT NULL,
  PRIMARY KEY (`id_reclamacoes`),
  INDEX `fk_usuarios_idx` (`fk_usuarios` ASC),
  INDEX `fk_empresas_idx` (`fk_empresas` ASC),
  CONSTRAINT `fk_usuarios`
    FOREIGN KEY (`fk_usuarios`)
    REFERENCES `portal_cidadao`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresas`
    FOREIGN KEY (`fk_empresas`)
    REFERENCES `portal_cidadao`.`empresas` (`id_empresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `portal_cidadao`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `portal_cidadao`;
INSERT INTO `portal_cidadao`.`usuarios` (`id_usuario`, `nome_usuario`, `nome_completo`, `senha`) VALUES (1, 'beasicas', 'Beatriz Siqueira Costa', '123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `portal_cidadao`.`empresas`
-- -----------------------------------------------------
START TRANSACTION;
USE `portal_cidadao`;
INSERT INTO `portal_cidadao`.`empresas` (`id_empresas`, `nome_empresa`, `login`, `senha`, `cnpj`) VALUES (1, 'CEMIG Teófilo Otoni', 'cemig.to', '123', '68.681.493/0001-06');
INSERT INTO `portal_cidadao`.`empresas` (`id_empresas`, `nome_empresa`, `login`, `senha`, `cnpj`) VALUES (2, 'COPASA Teófilo Otoni', 'copasa.to', '123', '23.124.142/0001-04');

COMMIT;

